name: Test/Build/Deploy
on:
  push:
  pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@cable-shared-worker'
          node-version-file: '.tool-versions'

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: Run eslint
        run: yarn lint

      - name: Run tests
        run: yarn test

  release:
    name: "Release"
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@cable-shared-worker'
          always-auth: true
          node-version-file: '.tool-versions'

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: Build all files
        run: yarn build

      - name: Setup yarn publish settings
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmPublishAccess "public"

      - name: Publish packages 🚀
        run: yarn workspaces foreach -W --no-private npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

